### PR TITLE
[WIP] Submitting Planning Session Notes - May, 2019 

### PR DESCRIPTION
**Pull request by TimTor**
Submitting Planning Session Notes - May, 2019

### CODE REVIEW

**Comment by dasanchez** [comment]
@TimTor can you update the governance structure doc as well please?

**Review by dasanchez — APPROVED** [review]
Thanks a bunch!

**Comment by makew0rld** [comment]
Looks good, but should all references to Tim be changed to TimTor in light of his Github username, or does it not matter? Is there a standard?

**Comment by Shrinks99** [comment]
> Looks good, but should all references to Tim be changed to TimTor in light of his Github username, or does it not matter? Is there a standard?

AFAIK it was the name used on Riot and not GitHub which tripped me up too and I asked this question last time.  Either way, now ya know!

**Pull request merged**
