### PR TITLE
Add results from Gigabit Link Field Test

### PR DESCRIPTION
**Pull request by benhylau**
If people doing the drop pins can update with exact distances that'd be great.

### CODE REVIEW

**Comment by ansuz** [comment]
TWBG

**Comment by dcwalk** [comment]
@uditvira do you have the coords for the test distances? I only had the one, wasn't sure how you wanted to add

**Comment by uditvira** [comment]
### Here are the coordinate I have:
- Station anchored at: `43.645771, -79.320951`
- 1st test location: `43.643781,-79.321583`
- 2nd test location: `43.641396, -79.322121`
- 3rd test location (no line of sight): `43.638118, -79.322729`
- we also did another check without line of sight while walking back at: `43.639665, -79.322247`

### These are the calculated distances:
- Station to 1st location: `227 m`
- Station to 2nd location: `596 m`
- Station to 3rd location: `863 m`
- Station to interim walk back location: `687 m`

@benhylau or @dcwalk  can we update the results document with these?

**Comment by benhylau** [comment]
@uditvira I have no data at 687 m so I will just omit that one. Will update with the rest.

**Comment by ansuz** [comment]
:+1:

**Comment by benhylau** [comment]
Please go ahead and merge if this looks okay

**Pull request merged**
