### PR TITLE
Add docs for Wekan usage and set up

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by dcwalk** [comment]
LGTM 👍 , though I think some of the usage comments belong on the website, not in service setup....? We eventually need to have a "ways to be involved/contribute" I think.

**Comment by benhylau** [comment]
@dcwalk Agreed. Feel free to move **Usage** over when we update website / rewrite the **README.md**.

**Comment by dcwalk** [comment]
@benhylau does anything need to change under setup with the updates for SSL config?

**Comment by benhylau** [comment]
@dcwalk yea @garrying sent me detailed steps, will update when I get a chance

**Pull request merged**
