### PR TITLE
2019-07-10 mesh-sync

### PR DESCRIPTION
**Pull request by darkdrgn2k**

### CODE REVIEW

**Review by dasanchez — APPROVED** [review]
Thanks @darkdrgn2k

**Comment by Hurricos** [comment]
I pushed a small edit correcting some info about the Ramble. (The mesh never actually got deployed, which was fine as there would not have been any space for bikes.) 

We did set up a normal 802.11s + wire mesh, and served our public WiFi network over it, with some usage.

**Review by Hurricos — APPROVED** [review]
All cool after update!

**Review by TimTor — APPROVED** [review]
Added my notes

**Pull request merged**
