### PR TITLE
Add summary of Toronto Mesh infrastructural services

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by benhylau** [comment]
Can someone approve and merge?

**Comment by benhylau** [comment]
In the future I think we should break out mesh-only services to another table, or have some way to indicate `h.` and `y.` availability on this one. But I rather get this reviewed and merged as is, so at least we got something to track!

**Comment by makew0rld** [comment]
Shouldn't `y.chat.tomesh.net` and the `h` equivalent be added too?

**Comment by benhylau** [comment]
@makeworld-the-better-one yes, I wonder if this should be a separate or same table. It gets a little confusing in the same table, when people aren't sure what `y.` and `h.` mean. I was hoping to merge this then someone can take care of the mesh-only services.

**Comment by benhylau** [comment]
Approve?

**Review by makew0rld — APPROVED** [review]

**Pull request merged**
