### PR TITLE
Funding

### PR DESCRIPTION
**Pull request by SeaPancakes**
Summary of funding opportunities pursued by ToMesh.
Contact: funding@tomesh.net

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @SeaPancakes thanks! It looks like the file name got truncated as "Fun" can you correct?
As it is in your repo I can't push changes to the branch. It might make sense to update the file (something like "`funding.md`") and then we can get it added and take any next changes from there?

**Comment by benhylau** [comment]
Please add `Contact` column as discussed before, since there may be different people responsible for each grant application.

We previously agreed on:

| Name | Due Date | Status | Contact |
| --- | --- | --- | --- |

The revised version + `Contact` looks good to me as well:

| Name of Opportunity | Organization | Due Date | Progress | Contact |
| --- | --- | --- | --- | --- |

**Comment by benhylau** [comment]
@SeaPancakes Rendering is messed up https://github.com/SeaPancakes/documents/blob/2c7af150de4346a7ad8032eb1ad56282b2e89868/governance/funding.md need newline (or I think a tab) after the lines.

For **Contact** I was thinking to put name of person responsible for submitting the particular grant. Even though all emails are directed to funding [at] tomesh.net. Does that make sense or is it very confusing?

**Comment by dcwalk** [comment]
Going to merge and then resolve formatting in a new PR.

**Pull request merged**
