### PR TITLE
added notes from apr 5 meeting

### PR DESCRIPTION
**Pull request by dcwalk**
Just testing this out, think it would be a good idea to have a recap/notes from out meeting public.

Didn't add any identifying info, I think going forward we could:
-ask at a meeting if we could list people as attending publicly
-make clear some notes will be published publicly
-embed images!

### CODE REVIEW

**Comment by garrying** [comment]
Were you anticipating more folders? I wonder if notes could just sit in the top-level.

**Comment by patcon** [comment]
:+1: for yaml front-matter :)

**Comment by benhylau** [comment]
Shall we link the Problem Definition gdoc? lgtm otherwise

**Comment by dcwalk** [comment]
@garrying I actually think the repo title is a placeholder -- I assume we will have some other important docs that should be publicly posted too and hence the initial folder, I can collapse for now though.
@benhylau I held off because I wasn't sure if that would be a stable doc, I guess that doesn't matter though so, as it is helpful for anyone looking NOW while the doc is still live -- also, it does have people's public info (your email/gmail accts, are we cool with those being public?)

**Comment by benhylau** [comment]
@dcwalk Thought if we take the approach of publishing as much info as possible regardless whether things are "final" or not, the process could be more inclusive. Say for example, if someone sees the current meeting notes and would like to dig deeper into the Problem Definition, they'd currently hit a dead end beyond the few summary points we posted. But if there's a link, they can see everything referred to and will potentially make an anonymous edit. I think the important thing is to mark things as publicly visible (which the Google Doc already did) and mark transient things as WIP.

In this case, we didn't beforehand discuss whether the gdoc edits will be public, so the account privacy concerns are valid and we can keep it private for now unless all contributors have no problem publishing it.

**Comment by garrying** [comment]
@dcwalk That makes sense to me! We can make use of `readme.md` to point where notes/docs/images are going.

**Comment by dcwalk** [comment]
great! everyone who had contributed to the Problem Definition doc was okay with it being linked publicly so I've added. Gonna merge this in as you've all reviewed (thanks btw!)

**Pull request merged**
