### PR TITLE
Add code of conduct to documents

### PR DESCRIPTION
**Pull request by dcwalk**
Please provide feedback. I worked from the source douments for the civic tech code of conduct. 

I think we need to think how to speak to organizers/who is an organizer...
Also @benhylau I believe the language reflects your comments around the spaces that this would be expected to cover.

### CODE REVIEW

**Comment by benhylau** [comment]
Thanks for putting this together. This looks great :)

Thoughts on _organizer_... Though the Toronto Mesh has an open membership, as in anyone can freely join, any particular event/chat/forum is probably organized or moderated by a small group of people. So that group would be the _organizer_ for that specific gathering of people. Now since anyone may join the mesh, thus becoming a _member_, and any member may hold an event or offer an online gathering place, there is no centralized mechanism to enforce adoption or enforcement of the Conduct. This is not to say a Conduct is pointless. Rather, assuming that the participants of the gathering are committed to the Conduct, it's their responsibility to _walk out_ when the organizers fail to enforce the rules. Of course, there is also no way to ensure participants will do this. But at this point, whoever remains have consciously decided to violate the Toronto Mesh Conduct pledge, and whatever guidelines that group observes no longer represents the Toronto Mesh. It is essentially a fork of the Toronto Mesh community with differing views in what is appropriate conduct.

**Comment by dcwalk** [comment]
@benhylau been thinking a lot about your comments -- I'm not sure I entirely understand, and so with that in mind...

I'm extremely uneasy about placing the onus on individuals entering a space to 'fork it' in the face of inappropriate behaviour, I may understanding this part of your comment. I also feel like standards actively decided on by active members in the community are more than fine point to and say: this is what we think tomesh's space should be (e.g. welcoming) and if people want to use the name in anything they plan, they'll have to agree with us (leaving aside the fact that people all the time use names in a manner not intended).

I get the sense that you are discussing almost a decentralized CoC (and referencing enforcement)? Which I think lacks the required level of intentionality that creating a welcoming space would require, of which a CoC is only one part of.

An example of a recent code of conduct development process that I think captures the kind of intentionality around creating a welcoming space is [here](https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct).

**Comment by benhylau** [comment]
I am referring to _membership_ as anyone who is connected to the mesh network, which may be someone distant from the group here that decided on the CoC. My concern is around enforcement of the CoC in spaces where a member hosts a particular event, fails to properly address inappropriate behaviour, but yet we have no control over.

For example, someone can run a forum on the mesh network, refuses to moderate in accordance with the CoC, and yet we have no control over to their membership in the network.

> if people want to use the name in anything they plan, they'll have to agree with us

Yes, we can claim that platforms that do not respect the CoC here are not representative of what the Toronto Mesh organization believes, but we have no way to influence the continued existence of such platforms. It's up to participants to choose either to stick with it or leave to a more welcoming space.

If I understand correctly, the Public Lab's CoC describes a Moderation Group that can influence access permission of members. But in a project that's missing this centralized control, I am not sure what mechanism may ensure the CoC is respected and enforced in all spaces.

> placing the onus on individuals entering a space to 'fork it' in the face of inappropriate behaviour

I mean that the organizers are expected to handle inappropriate behaviour, but when that does not happen, there is responsibility on all the participants' part to raise the concern that this is no longer a welcoming space. I just do not see another way of enforcing a CoC.

**Comment by benhylau** [comment]
@dcwalk Can we merge this in?

**Comment by dcwalk** [comment]
@benhylau I wasn't entirely happy with this and other people wanted to discuss the best way to implement/CoCs more generally. There hasn't been any feedback so I'm not sure how to proceed.

I think we could set a time to have this conversation (maybe at ctto) and hash out a first version to operate by (which would basically be confirming some details).

**Comment by dcwalk** [comment]
I've updated the code of conduct based on our planning meeting, this recent commit just addresses enforcement but leaves the remaining intact. 

I'm going to pull a doc in for guidelines RE: reports and managing the email shortly

**Comment by dcwalk** [comment]
Okay @benhylau this is ready for review, also @ansuz if you have any thoughts they'd be welcome

**Comment by juanc1t0** [comment]
Looks good to me - I can't think of anything to add. Thanks! - Jon

**Comment by dcwalk** [comment]
Thanks @juanc1t0 for taking the time to review 😄

**Comment by benhylau** [comment]
This looks great! Thanks @dcwalk

**Comment by ansuz** [comment]
:+1:

**Pull request merged**
